version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:8.0.28
    ports:
      - '3305:3305'
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: austin
      MYSQL_PASSWORD: poto24601
      MYSQL_ROOT_PASSWORD: poto24601
    volumes:
      - ./data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      maxClientCnxns: 1000
    ports:
      - 22181:2181
    volumes:
      - ./data:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - ./data:/var/lib/kafka
    command:
      sh -c "sleep 10 && /etc/confluent/docker/run"